### ISSUE TITLE
I couldn't understand your logic here.

### ISSUE THREAD

**Issue by alqurri77** [hamidriasat/UNet-3-Plus#1]
Hi;

I'm  not trying to point to any issue. I just couldn't understand your logic. My understanding is in any Unet you need both the output of pooling (for downward path) and output of convolution for the skip connection. so some thing like this:

`c1, p1 = down_block(p0, f[1])`

But I notice in your code your are overwriting the skip value, like this:

```
e2 = k.layers.MaxPool2D(pool_size=(2, 2))(e1)  # 160*160*64
e2 = conv_block(e2, filters[1])                    # 160*160*128

```

here e1 gets overwritten, which confuse me. I hope my question is clear.

Thank you!

**Comment by hamidriasat** [comment]
Hi

i have verified it from the original UNET3+ repository there is nothing wrong in the implementation.
For further details you can check the [UNet 3+](https://arxiv.org/abs/2004.08790) paper, i don't have time to share the exact details because i am working on things. 

Thanks

**Comment by dcsolus** [comment]
I guess Hamidriasast has done right, following the model design.

Hi there,
just a quick silly question about cat_channel and cat_blocks. What does 'cat' stand for when you name those variables? Is it 'category'?

**Comment by hamidriasat** [comment]
Hi, @dcsolus thanks for the confirmation on model design.

It's been a while, I don't recall things exactly. But I think 'cat' was referring to 'concatenation'. The idea was to specify number of channels/kernels that will be concatenated at the decoder side.
