### ISSUE TITLE
tiny little typos

### ISSUE THREAD

**Issue by dcsolus** [hamidriasat/UNet-3-Plus#2]
This code reads very well. It's nicely coded and easy to read and understand the whole idea of the U-Net3+. So many thanks to you.

I just want to let you know that there might be some typos. 

d4_d3 = k.layers.UpSampling2D(size=(2, 2), interpolation='bilinear')(d4)  
d4_d3 = conv_block(d4_d3, cat_channels, n=1)       

I guess all 'd4's should be 'e4'
e4_d3 = k.layers.UpSampling2D(size=(2, 2), interpolation='bilinear')(e4)     
e4_d3 = conv_block(e4_d3, cat_channels, n=1)

**Comment by hamidriasat** [comment]
Thanks for the encouraging words.

You were right, variable names are changed as you mentioned.
