### ISSUE TITLE
error  :batch_images[i] = image ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by wanghuaiji** [hamidriasat/UNet-3-Plus#5]
File "/home/whj2023/unet3/unet3/data_generator.py", line 79, in __getitem__
    return self.__data_generation(indexes)
  File "/home/whj2023/unet3/unet3/data_generator.py", line 144, in __data_generation
    batch_images[i] = image
ValueError: setting an array element with a sequence.

why?

**Comment by hamidriasat** [comment]
@wanghuaiji Kindly share some details about the experiment settings in which you received this error, or you should share Colab with this error so that I can debug it.
